add_products_to_cart:
  path: /api/v1/clientReading/{clientReadingId}/readings/
  controller: App\Controller\Api\SuspiciousReaginDetector\ClientReading\AddReadingToClientReadingController.php
  methods: POST